# Generated by Django 4.2.5 on 2023-10-09 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionTHC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TalentoHumano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('idType', models.CharField(choices=[('Cedula de Ciudadania', 'Cedula de Ciudadania'), ('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('Cedula de Extranjeria', 'Cedula de Extranjeria'), ('Pasaporte', 'Pasaporte'), ('Registro Civil', 'Registro Civil'), ('No. Unico de Id. Personal', 'No. Unico de Id. Personal'), ('Per Especial Permanencia', 'Per Especial Permanencia'), ('Permiso por Proteccion Temporal', 'Permiso por Proteccion Temporal')], max_length=100)),
                ('document', models.CharField(max_length=100, unique=True)),
                ('docExpeditionDate', models.DateField(blank=True)),
                ('expeditionPlace', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('secondName', models.CharField(blank=True, max_length=100, null=True)),
                ('firstLastname', models.CharField(max_length=100)),
                ('secondLastname', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(choices=[('M', 'M'), ('H', 'H'), ('Otro', 'Otro')], max_length=100)),
                ('birthday', models.DateField(blank=True)),
                ('birthPlace', models.CharField(max_length=100)),
                ('residenceAddress', models.CharField(max_length=100)),
                ('municipalitieResidence', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('contactPhone', models.CharField(max_length=20)),
                ('personalEmail', models.EmailField(max_length=254)),
                ('professionalEmail', models.EmailField(max_length=254, null=True)),
                ('escolaridad', models.CharField(choices=[('Primaria', 'Primaria'), ('Bachillerato', 'Bachillerato'), ('Practicante', 'Practicante'), ('Pregrado', 'Pregrado'), ('Postgrado', 'Postgrado')], max_length=100)),
                ('profesion', models.CharField(max_length=100, null=True)),
                ('estadoCivil', models.CharField(choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viudo(a)', 'Viudo(a)'), ('Union Libre', 'Union Libre')], max_length=100)),
                ('bloodGroup', models.CharField(max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('eps', models.CharField(max_length=100)),
                ('afs', models.CharField(max_length=100)),
                ('codigoCentroTrabajo', models.CharField(max_length=100)),
                ('codigoActividadDesarrollar', models.CharField(max_length=100)),
                ('contractType', models.CharField(choices=[('Contrato Termino Fijo', 'Contrato Termino Fijo'), ('Contrato Prestación de Servicios', 'Contrato Prestación de Servicios'), ('Contrato Tiempo Parcial', 'Contrato Tiempo Parcial'), ('Contrato a Termino Indefinido', 'Contrato a Termino Indefinido'), ('Contrato Practicante', 'Contrato Practicante')], max_length=100)),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Remoto', 'Remoto'), ('Mixto', 'Mixto')], max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('jornada', models.CharField(max_length=100)),
                ('startDate', models.DateField(blank=True)),
                ('endDate', models.DateField(blank=True)),
                ('monthlySalary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('totalSalary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('functions', models.TextField(blank=True)),
                ('contractsObject', models.TextField(blank=True)),
                ('lugarPrestacionServicios', models.CharField(max_length=100)),
                ('departamentoPrestacionServicios', models.CharField(max_length=100)),
                ('paymentMethod', models.CharField(max_length=100)),
                ('drivingLicense', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('titulos', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('disabilityCertificate', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('confidentialityCompromise', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('resume', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('idPicture', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('updatedRut', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('libretaMilitar', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('professionalCard', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('medicalCertificate', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('vpnCertificate', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('treatmentAuthorization', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('laborCertificate', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('sexualFormat', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
                ('audioPhotoAuthorization', models.FileField(blank=True, max_length=254, null=True, upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=100, unique=True)),
                ('red', models.CharField(max_length=100)),
                ('contractType', models.CharField(choices=[('Contrato', 'Contrato'), ('Convenio', 'Convenio'), ('Otro', 'Otro')], max_length=100)),
                ('userType', models.CharField(choices=[('Admin', 'Admin'), ('General', 'General'), ('Auxiliar', 'Auxiliar')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveBigIntegerField(default=2023)),
                ('contractType', models.CharField(choices=[('Contrato', 'Contrato'), ('Convenio', 'Convenio'), ('Otro', 'Otro')], max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('minimumSalary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contractValueSMMLV', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contractorsBudget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('redsBudget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('startDate', models.DateField(blank=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('secop', models.CharField(max_length=100)),
                ('rup', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100, unique=True)),
                ('contractor', models.CharField(max_length=100)),
                ('departments', models.TextField(blank=True)),
                ('municipalities', models.TextField(blank=True)),
                ('topic', models.CharField(max_length=100)),
                ('object', models.TextField(blank=True)),
                ('resultsIndicator', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('talentohumanos', models.ManyToManyField(through='tasks.RelacionTHC', to='tasks.talentohumano')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='talentohumano',
            name='tasks',
            field=models.ManyToManyField(through='tasks.RelacionTHC', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='relacionthc',
            name='talentoHumano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.talentohumano'),
        ),
        migrations.AddField(
            model_name='relacionthc',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
