# Generated by Django 4.2.5 on 2023-10-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionthc',
            name='contractType',
            field=models.CharField(choices=[('Contrato Termino Fijo', 'Contrato Termino Fijo'), ('Contrato Prestación de Servicios', 'Contrato Prestación de Servicios'), ('Contrato Tiempo Parcial', 'Contrato Tiempo Parcial'), ('Contrato a Termino Indefinido', 'Contrato a Termino Indefinido'), ('Contrato Practicante', 'Contrato Practicante')], default='Contrato Termino Fijo', max_length=100),
        ),
        migrations.AddField(
            model_name='relacionthc',
            name='modalidad',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Remoto', 'Remoto'), ('Mixto', 'Mixto')], default='Presencial', max_length=100),
        ),
    ]
