# Generated by Django 4.2.5 on 2023-10-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_relacionthc_cargo_relacionthc_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionthc',
            name='contractsObject',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='relacionthc',
            name='departamentoPrestacionServicios',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='relacionthc',
            name='functions',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='relacionthc',
            name='lugarPrestacionServicios',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='relacionthc',
            name='monthlySalary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='relacionthc',
            name='paymentMethod',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='relacionthc',
            name='totalSalary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='relacionthc',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='relacionthc',
            name='endDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='relacionthc',
            name='jornada',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='relacionthc',
            name='startDate',
            field=models.DateField(blank=True),
        ),
    ]
