# Generated by Django 4.2.5 on 2023-10-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_files_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_made', models.DateTimeField(auto_now_add=True)),
                ('talentohumano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.talentohumano')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
        ),
    ]
