# Generated by Django 4.2.5 on 2023-10-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentohumano',
            name='comment',
        ),
    ]
