# Generated by Django 4.2.5 on 2023-10-19 22:05

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_archivo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models.get_task_upload_path),
        ),
        migrations.AlterField(
            model_name='talentohumano',
            name='audioPhotoAuthorization',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=tasks.models.get_talentohumano_upload_path),
        ),
        migrations.AlterField(
            model_name='talentohumano',
            name='confidentialityCompromise',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=tasks.models.get_talentohumano_upload_path),
        ),
        migrations.AlterField(
            model_name='talentohumano',
            name='disabilityCertificate',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=tasks.models.get_talentohumano_upload_path),
        ),
        migrations.AlterField(
            model_name='talentohumano',
            name='drivingLicense',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=tasks.models.get_talentohumano_upload_path),
        ),
        migrations.AlterField(
            model_name='talentohumano',
            name='idPicture',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=tasks.models.get_talentohumano_upload_path),
        ),
        migrations.AlterField(
            model_name='talentohumano',
            name='laborCertificate',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=tasks.models.get_talentohumano_upload_path),
        ),
        migrations.AlterField(
            model_name='talentohumano',
            name='libretaMilitar',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=tasks.models.get_talentohumano_upload_path),
        ),
        migrations.AlterField(
            model_name='talentohumano',
            name='medicalCertificate',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=tasks.models.get_talentohumano_upload_path),
        ),
        migrations.AlterField(
            model_name='talentohumano',
            name='professionalCard',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=tasks.models.get_talentohumano_upload_path),
        ),
        migrations.AlterField(
            model_name='talentohumano',
            name='resume',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=tasks.models.get_talentohumano_upload_path),
        ),
        migrations.AlterField(
            model_name='talentohumano',
            name='sexualFormat',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=tasks.models.get_talentohumano_upload_path),
        ),
        migrations.AlterField(
            model_name='talentohumano',
            name='titulos',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=tasks.models.get_talentohumano_upload_path),
        ),
        migrations.AlterField(
            model_name='talentohumano',
            name='treatmentAuthorization',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=tasks.models.get_talentohumano_upload_path),
        ),
        migrations.AlterField(
            model_name='talentohumano',
            name='updatedRut',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=tasks.models.get_talentohumano_upload_path),
        ),
        migrations.AlterField(
            model_name='talentohumano',
            name='vpnCertificate',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to=tasks.models.get_talentohumano_upload_path),
        ),
    ]
