# Generated by Django 4.2.5 on 2023-10-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_archivo_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contractType',
        ),
    ]
