# Generated by Django 4.2.5 on 2023-10-25 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0015_alter_usuario_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveBigIntegerField(default=2023)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('Externa', 'Externa'), ('Interna', 'Interna')], max_length=100, null=True)),
                ('dateCreated', models.DateField(blank=True)),
                ('sentTo', models.CharField(max_length=100)),
                ('areaProject', models.CharField(max_length=100)),
                ('asunto', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
