# Generated by Django 4.2.5 on 2023-10-26 21:41

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_correspondencia_sequence_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models.get_correspondencia_upload_path),
        ),
    ]
