# Generated by Django 4.2.5 on 2023-10-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_correspondencia_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correspondencia',
            old_name='sequence_number',
            new_name='sequence_number_ext',
        ),
        migrations.AddField(
            model_name='correspondencia',
            name='sequence_number_int',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
