# Generated by Django 4.2.5 on 2023-11-02 20:25

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_alter_task_contracttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='resultsIndicator',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models.get_task_upload_path),
        ),
    ]
