# Generated by Django 4.2.5 on 2023-11-07 14:02

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_alter_task_resultsindicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='resultsIndicator',
            field=models.FileField(blank=True, null=True, upload_to=tasks.models.get_coso_upload_path),
        ),
        migrations.AlterUniqueTogether(
            name='relacionthc',
            unique_together={('talentoHumano', 'task')},
        ),
    ]
