# Generated by Django 4.2.5 on 2023-11-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='caracteristicas',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='dateAdquired',
            field=models.DateField(blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='dateGivenBack',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='dateTaken',
            field=models.DateField(blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='entregadoA',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Averiado/Dañado', 'Averiado/Dañado')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='marca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='redProject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='serial_num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1.00, max_digits=14),
            preserve_default=False,
        ),
    ]
