# Generated by Django 4.2.5 on 2023-11-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_inventario_cantidad_inventario_caracteristicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='dateAdquired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='dateTaken',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='entregadoA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='serial_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
