# Generated by Django 4.2.5 on 2023-11-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_alter_inventario_dateadquired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='dateTaken',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='entregadoA',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
