# Generated by Django 4.2.5 on 2023-11-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_alter_inventario_datetaken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='prestado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
