# Generated by Django 4.2.5 on 2023-11-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_inventario_prestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='entregadoA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
