# Generated by Django 4.2.5 on 2023-11-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_alter_inventario_entregadoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='redProject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
