# Generated by Django 4.2.5 on 2023-11-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_alter_inventario_redproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='name',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
