# Generated by Django 4.2.5 on 2023-11-08 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_inventario_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField()),
                ('entregadoA', models.CharField(blank=True, max_length=100, null=True)),
                ('redProject', models.CharField(blank=True, max_length=100, null=True)),
                ('dateTaken', models.DateField()),
                ('dateGivenBack', models.DateField()),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.inventario')),
            ],
        ),
    ]
