# Generated by Django 4.2.5 on 2023-11-22 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0044_cede'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cede',
            new_name='Sede',
        ),
    ]
