# Generated by Django 4.2.5 on 2023-11-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0049_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('Completada', 'Completada'), ('Pendiente', 'Pendiente')], max_length=100),
            preserve_default=False,
        ),
    ]
