# Generated by Django 4.2.5 on 2023-11-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0050_visita_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='observacionGeneral',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_10_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_10_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_10_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_10_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_10_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_11_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_11_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_11_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_11_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_11_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_11_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_11_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_11_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_11_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_11_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_1_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_1_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_1_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_1_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_1_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_1_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_1_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_2_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_2_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_2_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_2_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_2_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_2_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_2_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_2_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_2_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_3_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_3_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_3_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_3_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_3_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_3_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_3_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_3_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_4_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_4_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_4_11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_4_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_4_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_4_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_4_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_4_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_4_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_4_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_4_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_5_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_6_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_6_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_6_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_6_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_7_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_7_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_7_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_7_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_8_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_8_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_8_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_8_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_8_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_9_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacion_9_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
