# Generated by Django 4.2.5 on 2023-11-24 16:07

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0052_otrafoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='visita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='tasks.visita'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=tasks.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='foto',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='tasks.sede'),
        ),
        migrations.DeleteModel(
            name='OtraFoto',
        ),
    ]
