# Generated by Django 4.2.5 on 2023-11-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0053_foto_visita_alter_foto_file_alter_foto_sede_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='visita',
        ),
    ]
