# Generated by Django 4.2.5 on 2023-11-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0054_remove_foto_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='visita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='tasks.visita'),
        ),
    ]
